# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  codecov: codecov/codecov@1.0.4

commands:
  setup-repo:
    description: "Install dependencies, cache them, bootstrap packages"
    steps:
      - checkout
      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-
      - run: 
          name: Install dependencies
          command: npm ci
      - run:
          name: Bootstrap packages
          command: npm run bootstrap
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

jobs:
  build:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/repo
    steps:
      - setup-repo
      - run:
          name: Build with rollup
          command: npm run build

  test:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - setup-repo
      - run:
          name: Lint source code
          command: npm run lint
      - run:
          name: Run tests and generate coverage
          command: npm run test:cov
      - codecov/upload:
        file: { { coverage_report_filepath } }
  deploy:
    docker:
      - image: circleci/node:10.15.3
    steps:
      - setup-repo
      - run:
          name: Authenticate with registry
          command: echo "//registry.npmjs.org/:_authToken=$npm_TOKEN" > ~/repo/.npmrc
      - run: 
          name: Publish all changed packages
          command: lerna publish

workflows:
  version: 2
  buildTestDeploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - deploy:
          requires:
            - build